spring:
  application:
    name: analitics-service

server:
  port: 8764

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka/